name: test

on:
  push:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Costco iOS branch name'
        required: true
        default: 'develop'
        type: string
env:
  BUILD_NUMBER: ${{ github.run_number }}
  ENTERPRISE_TEAM_ID: 'TGWXEY4D6F'
  APPSTORE_TEAM_ID: 'MCL67DL73Q'
  XCODE_VERSION: '26.2'

jobs:
  checkout:
      name: checkout
      runs-on: macOS-15
      timeout-minutes: 180
      env:
        BRANCH_NAME: ${{ github.event.inputs.branch_name }}
        BUILD_NUMBER: ${{ github.run_number }}
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
            fetch-tags: false
            clean: true
        - name: Set SDK
          
          run: |
            set -e
            echo "Setting xcode version to: ${{ env.XCODE_VERSION }} .."
            sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app 
            _sdk="$(xcodebuild -showsdks | grep -i ios | grep -iv simulator | grep sdk | awk -F\"sdk\" '{print $NF}' | xargs || true)"
            echo "SDK=${_sdk}" >> $GITHUB_ENV
            echo "Detected SDK: $_sdk"
            xcodebuild -version
            xcrun simctl list runtimes
        - name: Install Distributions
          env:
            SDK: ${{ env.SDK }}
          run: |
            echo 'Setting xcode version: ${{ env.XCODE_VERSION }}'
            sudo xcode-select -switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app
            version=$(echo "$SDK" | grep -oE '[0-9]+\.[0-9]+')
            echo "$version"
            if xcrun simctl list runtimes | grep -Eq "\b${VERSION}\b"; then
              echo "Distribution SDK is already present"
            else
              echo "Required SDK not available, Installing the verson ${_sdk}"
              cpu_count=$(sysctl hw.ncpu | awk '{print $NF}')
              xcodebuild -downloadPlatform iOS -buildVersion $(version)
              echo "Installed the distributions "
            fi
        - name: Install GitHub CLI (if missing)
          run: |
              brew install gh