name: test

on:
  push:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Costco iOS branch name'
        required: true
        default: 'develop'
        type: string
env:
  BUILD_NUMBER: ${{ github.run_number }}
  ENTERPRISE_TEAM_ID: 'TGWXEY4D6F'
  APPSTORE_TEAM_ID: 'MCL67DL73Q'
  XCODE_VERSION: '26.2'

jobs:
  test:
      name: test
      runs-on: ubuntu-latest
      timeout-minutes: 180
      steps:
      - name: Set build version
        id: version
        env:
          MAJOR_MINOR: ${{ vars.MAJOR_MINOR || '26.6.1' }}
          ADO_BUILD_OFFSET: ${{ vars.ADO_BUILD_OFFSET || '65000' }}          
        run: |
          #!/bin/bash
          set -e
          version=""
          BUILD_NUMBER=$(( ADO_BUILD_OFFSET + ${{ github.run_number }} ))
          version="${MAJOR_MINOR}.${BUILD_NUMBER}"
          echo "APK version: $version"
          echo "Build number: ${BUILD_NUMBER}"
          echo "APK_VERSION=$version" >> $GITHUB_OUTPUT
          echo "APK_VERSION=$version" >> $GITHUB_ENV
          mkdir -p "$RUNNER_TEMP/artifacts"
          echo "$version" > "$RUNNER_TEMP/artifacts/apk_version"
          
